version: "3.8"
services:
  redis:
    image: redis:7.0.4
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
      - "9160:9160"
    volumes: 
      - cassandra:/var/lib/cassandra
volumes:
  postgres:
    driver: local
  cassandra:
    driver: local

 
